import type { QuoteFlowState, QuoteLine } from "@/lib/quoteflow-types"

const line = (overrides: Partial<QuoteLine> & Pick<QuoteLine, "id" | "description">): QuoteLine => ({
  quantity: 1,
  unit: "lotto",
  material: "S235JR",
  processes: "Taglio laser, piegatura",
  materialCost: 680,
  machineHours: 6,
  machineRate: 68,
  laborHours: 5,
  laborRate: 42,
  externalCost: 0,
  extraCost: 45,
  ...overrides,
})

export const DEMO_STATE: QuoteFlowState = {
  clients: [
    { id: "c1", company: "Alfa Demo Automazioni S.r.l.", contact: "Referente Demo 1", email: "referente1@example.com", phone: "+39 000 000 0001", city: "Bologna (BO)", vatNumber: "IT00000000001" },
    { id: "c2", company: "Beta Demo Packaging S.p.A.", contact: "Referente Demo 2", email: "referente2@example.com", phone: "+39 000 000 0002", city: "Pianoro (BO)", vatNumber: "IT00000000002" },
    { id: "c3", company: "Gamma Demo Impianti S.r.l.", contact: "Referente Demo 3", email: "referente3@example.com", phone: "+39 000 000 0003", city: "Modena (MO)", vatNumber: "IT00000000003" },
    { id: "c4", company: "Delta Demo Handling S.r.l.", contact: "Referente Demo 4", email: "referente4@example.com", phone: "+39 000 000 0004", city: "Calderara di Reno (BO)", vatNumber: "IT00000000004" },
    { id: "c5", company: "Epsilon Demo Officine S.n.c.", contact: "Referente Demo 5", email: "referente5@example.com", phone: "+39 000 000 0005", city: "Budrio (BO)", vatNumber: "IT00000000005" },
    { id: "c6", company: "Zeta Demo Robotics S.r.l.", contact: "Referente Demo 6", email: "referente6@example.com", phone: "+39 000 000 0006", city: "Bologna (BO)", vatNumber: "IT00000000006" },
    { id: "c7", company: "Eta Demo Metalform S.r.l.", contact: "Referente Demo 7", email: "referente7@example.com", phone: "+39 000 000 0007", city: "Imola (BO)", vatNumber: "IT00000000007" },
    { id: "c8", company: "Theta Demo Systems S.r.l.", contact: "Referente Demo 8", email: "referente8@example.com", phone: "+39 000 000 0008", city: "Reggio Emilia (RE)", vatNumber: "IT00000000008" },
  ],
  quotes: [
    { id: "q1", number: "PRV-2026-0184", date: "2026-09-03", validUntil: "2026-10-03", clientId: "c2", title: "Carter inox linea confezionamento", description: "Fornitura carter di protezione per nuova linea di confezionamento.", status: "Inviato", markup: 32, vat: 22, notes: "Consegna stimata: 4 settimane da ordine.", lines: [line({ id: "l1", description: "Carter inox piegato", quantity: 12, unit: "pz", material: "AISI 304 sp. 2 mm", processes: "Taglio laser, piegatura, satinatura", materialCost: 1480, machineHours: 13, laborHours: 11, externalCost: 240, extraCost: 90 })] },
    { id: "q2", number: "PRV-2026-0183", date: "2026-09-02", validUntil: "2026-10-02", clientId: "c1", title: "Telaio macchina pick-and-place", description: "Telaio saldato e verniciato per isola robotizzata.", status: "Accettato", markup: 38, vat: 22, notes: "Collaudo dimensionale incluso.", lines: [line({ id: "l2", description: "Telaio tubolare saldato", quantity: 2, unit: "pz", material: "S355J2", processes: "Taglio, saldatura MIG, fresatura, verniciatura", materialCost: 2180, machineHours: 18, laborHours: 26, externalCost: 620, extraCost: 150 })] },
    { id: "q3", number: "PRV-2026-0182", date: "2026-08-30", validUntil: "2026-09-29", clientId: "c6", title: "Piastre supporto robot", description: "Piastre lavorate CNC con forature e sedi di centraggio.", status: "Bozza", markup: 24, vat: 22, notes: "Tolleranze finali da confermare.", lines: [line({ id: "l3", description: "Piastra supporto robot", quantity: 8, unit: "pz", material: "Alluminio 6082 T6", processes: "Taglio, fresatura CNC, anodizzazione", materialCost: 920, machineHours: 19, machineRate: 74, laborHours: 6, externalCost: 360, extraCost: 55 })] },
    { id: "q4", number: "PRV-2026-0181", date: "2026-08-28", validUntil: "2026-09-27", clientId: "c4", title: "Protezioni per nastro trasportatore", description: "Ripari laterali zincati con staffe di fissaggio.", status: "Inviato", markup: 28, vat: 22, notes: "Imballo su pallet incluso.", lines: [line({ id: "l4", description: "Riparo laterale zincato", quantity: 24, unit: "pz", material: "DX51D Z275 sp. 1,5 mm", processes: "Taglio laser, piegatura", materialCost: 1260, machineHours: 15, laborHours: 9, externalCost: 0, extraCost: 120 })] },
    { id: "q5", number: "PRV-2026-0180", date: "2026-08-25", validUntil: "2026-09-24", clientId: "c3", title: "Vasche inox alimentari", description: "Vasche saldate a tenuta per impianto di processo.", status: "Accettato", markup: 42, vat: 22, notes: "Certificati materiale 3.1 inclusi.", lines: [line({ id: "l5", description: "Vasca inox saldata", quantity: 3, unit: "pz", material: "AISI 316L sp. 3 mm", processes: "Taglio laser, piegatura, saldatura TIG, decapaggio", materialCost: 3540, machineHours: 22, laborHours: 38, externalCost: 780, extraCost: 190 })] },
    { id: "q6", number: "PRV-2026-0179", date: "2026-08-20", validUntil: "2026-09-19", clientId: "c8", title: "Staffaggi linea etichettatura", description: "Serie di staffe regolabili per revamping linea.", status: "Rifiutato", markup: 31, vat: 22, notes: "Prezzo comprensivo di campionatura.", lines: [line({ id: "l6", description: "Kit staffaggi regolabili", quantity: 40, unit: "kit", material: "AISI 304", processes: "Laser, piegatura, saldatura", materialCost: 1980, machineHours: 21, laborHours: 24, externalCost: 0, extraCost: 220 })] },
    { id: "q7", number: "PRV-2026-0178", date: "2026-08-18", validUntil: "2026-09-17", clientId: "c5", title: "Ripristino basamento pressa", description: "Rinforzo e rilavorazione sedi su basamento esistente.", status: "Accettato", markup: 35, vat: 22, notes: "Intervento presso nostra sede.", lines: [line({ id: "l7", description: "Ripristino basamento", quantity: 1, unit: "intervento", material: "S355JR", processes: "Saldatura, distensione, lavorazione meccanica", materialCost: 740, machineHours: 17, laborHours: 29, externalCost: 480, extraCost: 85 })] },
    { id: "q8", number: "PRV-2026-0177", date: "2026-08-12", validUntil: "2026-09-11", clientId: "c7", title: "Contenitori lamiera verniciata", description: "Lotto contenitori per quadri bordo macchina.", status: "Inviato", markup: 12, vat: 22, notes: "Preventivo da rivedere: margine sotto soglia.", lines: [line({ id: "l8", description: "Contenitore quadro", quantity: 30, unit: "pz", material: "DC01 sp. 1,5 mm", processes: "Laser, piegatura, saldatura, verniciatura", materialCost: 2640, machineHours: 28, laborHours: 32, externalCost: 920, extraCost: 240 })] },
    { id: "q9", number: "PRV-2026-0176", date: "2026-07-29", validUntil: "2026-08-28", clientId: "c1", title: "Pannelli segregazione robot", description: "Pannelli modulari per protezione isola robotizzata.", status: "Accettato", markup: 36, vat: 22, notes: "RAL 7035.", lines: [line({ id: "l9", description: "Pannello modulare", quantity: 18, unit: "pz", material: "S235JR", processes: "Laser, piegatura, saldatura, verniciatura", materialCost: 1710, machineHours: 16, laborHours: 20, externalCost: 510, extraCost: 130 })] },
    { id: "q10", number: "PRV-2026-0175", date: "2026-07-18", validUntil: "2026-08-17", clientId: "c2", title: "Tramogge dosatrici", description: "Tramogge inox con finitura alimentare.", status: "Rifiutato", markup: 40, vat: 22, notes: "Trasporto escluso.", lines: [line({ id: "l10", description: "Tramoggia dosatrice", quantity: 4, unit: "pz", material: "AISI 316L", processes: "Laser, calandratura, TIG, satinatura", materialCost: 2920, machineHours: 24, laborHours: 35, externalCost: 420, extraCost: 110 })] },
  ],
  materials: [
    { id: "m1", name: "Lamiera S235JR sp. 2 mm", category: "Acciaio al carbonio", unit: "€/kg", price: 1.42 },
    { id: "m2", name: "Lamiera S355J2 sp. 5 mm", category: "Acciaio al carbonio", unit: "€/kg", price: 1.78 },
    { id: "m3", name: "AISI 304 2B sp. 2 mm", category: "Acciaio inox", unit: "€/kg", price: 4.9 },
    { id: "m4", name: "AISI 316L 2B sp. 3 mm", category: "Acciaio inox", unit: "€/kg", price: 7.35 },
    { id: "m5", name: "Alluminio 6082 T6", category: "Alluminio", unit: "€/kg", price: 5.8 },
    { id: "m6", name: "Tubolare 80×80×4 S355", category: "Profilati", unit: "€/m", price: 18.6 },
  ],
  processes: [
    { id: "p1", name: "Taglio laser fibra", category: "Macchina", unit: "€/h", price: 68 },
    { id: "p2", name: "Piegatura CNC", category: "Macchina", unit: "€/h", price: 62 },
    { id: "p3", name: "Fresatura CNC 3 assi", category: "Macchina", unit: "€/h", price: 74 },
    { id: "p4", name: "Saldatura MIG/MAG", category: "Manodopera", unit: "€/h", price: 44 },
    { id: "p5", name: "Saldatura TIG inox", category: "Manodopera", unit: "€/h", price: 48 },
    { id: "p6", name: "Montaggio e finitura", category: "Manodopera", unit: "€/h", price: 42 },
    { id: "p7", name: "Verniciatura a polvere", category: "Esterna", unit: "€/lotto", price: 280 },
    { id: "p8", name: "Zincatura elettrolitica", category: "Esterna", unit: "€/lotto", price: 190 },
  ],
  settings: {
    companyName: "FerroLab Demo",
    legalName: "FerroLab Demo S.r.l.",
    logoDataUrl: "",
    vatNumber: "IT00000000000",
    address: "Via Demo 1",
    city: "40000 Bologna (BO)",
    email: "preventivi@example.com",
    phone: "+39 000 000 0000",
    defaultMarkup: 32,
    minimumMargin: 24,
    defaultVat: 22,
    defaultMachineRate: 68,
    defaultLaborRate: 42,
    validityDays: 30,
    paymentTerms: "Bonifico bancario 30 gg data fattura",
    conditions: "Trasporto escluso salvo diversa indicazione. Tempi di consegna da confermare alla ricezione dell'ordine.",
  },
}
